language: python
before_install:
- pip install pycodestyle
- pip install pytest
- pip install pytest-cov
- pip install coveralls
- pip install sphinx
- pip install sphinx_rtd_theme
- pip install tpDcc-libs-unittests
install:
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --exclude */externals/* --max-line-length=120
  --ignore=E402 {} +
- pytest --cov=tpDcc
- sphinx-apidoc -f -e -o docs/sphinx tpDcc
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: YMEugxAGqPRPoRVElMqX5GWQXGRtMOiwDVqJcF8mjc0EPEkXhGnTWBtwctcKoFdn5Rr0TBqwrfhnjUJ52EEoop8R+tGjqURB4RNtu80RsUgDuXR04ssy6W0GOxkHqyrJO3DGYpbtokSz5D9zkiSByP4spuWfK4hC7dFNElm//z7fXIIl3oljmEoov214c5SQYoAqEAVCCpjp+p9jeS/PWfAJN7njjG7EraXRXHAeuck8ZR0PzvQA+HJcXc6N4vJntLEIFwBw/vq1iqIewNCrknjMPim4w3f0qIRHroaGMvxvpxvXGHQU9N+0PFdOA8EaSw2tw2Bp9EGHS28VpsrAWWuM0HeHRD6OBvdxFhdx7bUEr0VVx4habrozEI8IEQxxYbl8/V1sm66W6mZEIj2L9z4lSwU70C7pj5/2Dx4cBV40i32Xuttgn31dbVDzQnvZoud1SrRsQKxAh7A30rD9A1sUq+W6jNE+1DgoBZsS8J1RioMg5aStG7Df1YMnpN5ji8xgLfW5Bf7+Y4FJlMwZYeimXZ1dGZHw7UlZ294fsZQDxKG22IcLHmRZNB+zkihNs9qbw7g0eBXV41v2qnROObgVcKpZLZoyyjJgY5U8kHLBfFcROuW2c7QIEwxM/pVzXDf/3wDE5Rkw8CX0ajjjWqRZiSkMWlrPriMknH4e+nE=
    on:
      branch: master
      tags: true